--1.가장 늦게 입사한 직원의 이름과 연봉과 근무하는 부서이름은?

SELECT MAX(e.HIRE_DATE)  
FROM EMPLOYEES e;

SELECT e.FIRST_NAME, e.SALARY , d.DEPARTMENT_NAME , e.HIRE_DATE 
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.HIRE_DATE = (SELECT MAX(e.HIRE_DATE) FROM EMPLOYEES e)
AND e.DEPARTMENT_ID = d.DEPARTMENT_ID ;


--2.평균급여가 가장 높은 부서 직원들의
--직원번호, 이름, 성, 업무, 급여 조회하시오.

SELECT MAX(AVG(NVL(SALARY, 0))) 
FROM EMPLOYEES  
GROUP BY DEPARTMENT_ID; 


SELECT
	e.EMPLOYEE_ID ,
	e.FIRST_NAME ,
	j.JOB_TITLE  ,
	e.SALARY 
FROM 
	EMPLOYEES e , 
	JOBS j
WHERE e.JOB_ID = j.JOB_ID
AND e.DEPARTMENT_ID = 
	MAX() 